dataset: "webarena"
logging: True
verbose: 1
debug: False
logdir: "data/webarena/eval"
agent:
  type: "step" # "flat_fewshot8k", "flat_fewshot4k"
  root_action: 'shopping_agent'
  low_level_action_list: ['click', 'type', 'scroll', 'stop', 'goto', 'hover', 'note', 'go_back']
  # model_name: "gpt-4-turbo-2024-04-09"
  model_name: "gpt-3.5-turbo-0125"
  model_host: "openai"
  prompt_mode: "chat"
  max_target_len: 100
env:
  max_env_steps: 20
  max_browser_rows: 500
  headless: True
  task_ids: [44]
  task_ids_backup: [44, 132, 173, 784, 308, 169, 475, 481, 349, 293, 394]
