dataset: "webarena"
logging: True
verbose: 1
debug: False
logdir: "data/webarena/eval"
agent:
  type: "step" # "flat_fewshot8k", "flat_fewshot4k"
  root_action: 'shopping_agent'
  low_level_action_list: ['click', 'type', 'scroll', 'stop', 'goto', 'hover', 'note', 'go_back']
  # model_name: "gpt-4-turbo-2024-04-09"
  model_name: "gpt-3.5-turbo-0125"
  model_host: "openai"
  prompt_mode: "chat"
  max_target_len: 100
env:
  max_env_steps: 20
  max_browser_rows: 500
  headless: True
  task_ids: [168, 156, 357, 475, 480, 481, 349, 339, 45, 44, 441, 173, 259, 784, 205, 303, 132, 308, 314, 258, 658, 661, 293, 533, 448, 742, 666, 669, 590, 389, 102, 576, 394, 523, 411, 415, 418, 178, 799, 446, 747]
  task_ids_backup: [44, 45, 156, 258, 259, 132, 173, 784, 308, 169, 475, 481, 349, 293, 394]
